using Resend.Payloads;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

namespace Resend;

/// <summary>
/// Source-generated serialization metadata for Resend request/response payloads.
/// </summary>
[JsonSourceGenerationOptions( JsonSerializerDefaults.Web )]
[JsonSerializable( typeof( ErrorResponse ) )]
[JsonSerializable( typeof( ObjectId ) )]
[JsonSerializable( typeof( EmailReceipt ) )]
[JsonSerializable( typeof( PaginatedResult<EmailReceipt> ) )]
[JsonSerializable( typeof( ListOf<ObjectId> ) )]
[JsonSerializable( typeof( EmailBatchResponse ) )]
[JsonSerializable( typeof( EmailShareResult ) )]
[JsonSerializable( typeof( EmailMetrics ) )]
[JsonSerializable( typeof( PaginatedResult<SentEmailAttachment> ) )]
[JsonSerializable( typeof( SentEmailAttachment ) )]
[JsonSerializable( typeof( ListOf<Domain> ) )]
[JsonSerializable( typeof( Domain ) )]
[JsonSerializable( typeof( DomainClaim ) )]
[JsonSerializable( typeof( ApiKeyData ) )]
[JsonSerializable( typeof( ListOf<ApiKey> ) )]
[JsonSerializable( typeof( PaginatedResult<OAuthGrant> ) )]
[JsonSerializable( typeof( OAuthGrantRevoked ) )]
[JsonSerializable( typeof( Audience ) )]
[JsonSerializable( typeof( ListOf<Audience> ) )]
[JsonSerializable( typeof( Contact ) )]
[JsonSerializable( typeof( PaginatedResult<Contact> ) )]
[JsonSerializable( typeof( PaginatedResult<Segment> ) )]
[JsonSerializable( typeof( Segment ) )]
[JsonSerializable( typeof( SegmentUpdateResult ) )]
[JsonSerializable( typeof( PaginatedResult<TopicSubscription> ) )]
[JsonSerializable( typeof( PaginatedResult<ContactProperty> ) )]
[JsonSerializable( typeof( ContactProperty ) )]
[JsonSerializable( typeof( Broadcast ) )]
[JsonSerializable( typeof( ListOf<Broadcast> ) )]
[JsonSerializable( typeof( PaginatedResult<BroadcastRecipient> ) )]
[JsonSerializable( typeof( PaginatedResult<BroadcastClickedLink> ) )]
[JsonSerializable( typeof( Automation ) )]
[JsonSerializable( typeof( PaginatedResult<AutomationSummary> ) )]
[JsonSerializable( typeof( AutomationStopResult ) )]
[JsonSerializable( typeof( AutomationDeleteResult ) )]
[JsonSerializable( typeof( PaginatedResult<AutomationRunSummary> ) )]
[JsonSerializable( typeof( AutomationRun ) )]
[JsonSerializable( typeof( EventResource ) )]
[JsonSerializable( typeof( PaginatedResult<EventResource> ) )]
[JsonSerializable( typeof( EventDeleteResult ) )]
[JsonSerializable( typeof( EventSendResult ) )]
[JsonSerializable( typeof( PaginatedResult<Log> ) )]
[JsonSerializable( typeof( Log ) )]
[JsonSerializable( typeof( PaginatedResult<ReceivedEmail> ) )]
[JsonSerializable( typeof( ReceivedEmail ) )]
[JsonSerializable( typeof( PaginatedResult<ReceivedEmailAttachment> ) )]
[JsonSerializable( typeof( ReceivedEmailAttachment ) )]
[JsonSerializable( typeof( PaginatedResult<SuppressionSummary> ) )]
[JsonSerializable( typeof( Suppression ) )]
[JsonSerializable( typeof( SuppressionRemoveResult ) )]
[JsonSerializable( typeof( ListOf<SuppressionRemoveResult> ) )]
[JsonSerializable( typeof( PaginatedResult<TemplateSummary> ) )]
[JsonSerializable( typeof( Template ) )]
[JsonSerializable( typeof( PaginatedResult<Topic> ) )]
[JsonSerializable( typeof( Topic ) )]
[JsonSerializable( typeof( Usage ) )]
[JsonSerializable( typeof( PaginatedResult<Webhook> ) )]
[JsonSerializable( typeof( Webhook ) )]
[JsonSerializable( typeof( WebhookNew ) )]
[JsonSerializable( typeof( WebhookEventListResult ) )]
[JsonSerializable( typeof( WebhookEventDetails ) )]
[JsonSerializable( typeof( WebhookEventAttemptListResult ) )]
[JsonSerializable( typeof( EmailMessage ) )]
[JsonSerializable( typeof( IEnumerable<EmailMessage> ) )]
[JsonSerializable( typeof( List<TopicSubscription> ) )]
[JsonSerializable( typeof( ApiKeyCreateRequest ) )]
[JsonSerializable( typeof( ApiKeyUpdateRequest ) )]
[JsonSerializable( typeof( AudienceAddRequest ) )]
[JsonSerializable( typeof( BroadcastScheduleRequest ) )]
[JsonSerializable( typeof( BroadcastData ) )]
[JsonSerializable( typeof( BroadcastUpdateData ) )]
[JsonSerializable( typeof( AutomationCreateData ) )]
[JsonSerializable( typeof( AutomationUpdateData ) )]
[JsonSerializable( typeof( ContactData ) )]
[JsonSerializable( typeof( ContactPropertyData ) )]
[JsonSerializable( typeof( ContactPropertyUpdateData ) )]
[JsonSerializable( typeof( DomainAddData ) )]
[JsonSerializable( typeof( DomainClaimData ) )]
[JsonSerializable( typeof( DomainUpdateData ) )]
[JsonSerializable( typeof( EmailRescheduleRequest ) )]
[JsonSerializable( typeof( EmailShareRequest ) )]
[JsonSerializable( typeof( EventCreateData ) )]
[JsonSerializable( typeof( EventSendData ) )]
[JsonSerializable( typeof( EventUpdateData ) )]
[JsonSerializable( typeof( SegmentData ) )]
[JsonSerializable( typeof( SuppressionAddRequest ) )]
[JsonSerializable( typeof( SuppressionBatchAddRequest ) )]
[JsonSerializable( typeof( SuppressionBatchRemoveRequest ) )]
[JsonSerializable( typeof( TemplateData ) )]
[JsonSerializable( typeof( TopicData ) )]
[JsonSerializable( typeof( WebhookData ) )]
[JsonSerializable( typeof( string ) )]
[JsonSerializable( typeof( bool ) )]
[JsonSerializable( typeof( int ) )]
[JsonSerializable( typeof( long ) )]
[JsonSerializable( typeof( float ) )]
[JsonSerializable( typeof( double ) )]
[JsonSerializable( typeof( decimal ) )]
[JsonSerializable( typeof( DateTime ) )]
[JsonSerializable( typeof( DateTimeOffset ) )]
[JsonSerializable( typeof( DateOnly ) )]
[JsonSerializable( typeof( TimeOnly ) )]
[JsonSerializable( typeof( TimeSpan ) )]
[JsonSerializable( typeof( Guid ) )]
[JsonSerializable( typeof( JsonElement ) )]
[JsonSerializable( typeof( JsonNode ) )]
[JsonSerializable( typeof( JsonObject ) )]
[JsonSerializable( typeof( JsonArray ) )]
[JsonSerializable( typeof( Dictionary<string, object?> ) )]
[JsonSerializable( typeof( List<object?> ) )]
[JsonSerializable( typeof( object[] ) )]
internal partial class ResendJsonContext : JsonSerializerContext
{
}
